//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sm
    {
        public long Id { get; set; }
        public string ToNumber { get; set; }
        public string Contetns { get; set; }
        public System.DateTime Time { get; set; }
    }
}
